/**
 * G-code metadata parser — extracts slicer estimates from G-code comment headers.
 * Supports Bambu Studio, OrcaSlicer, PrusaSlicer, Cura, and SuperSlicer.
 */

export interface GcodeEstimates {
  weightG: number | null;
  printTimeMinutes: number | null;
  materialType: string | null;
  layerHeight: number | null;
  nozzleTemp: number | null;
  bedTemp: number | null;
  filename: string;
  slicer: string | null;
}

/**
 * Parse time strings like "1h 23m 45s", "1h23m45s", "83m 45s", "5040" (seconds).
 * Returns total minutes.
 */
function parseTimeString(timeStr: string): number | null {
  // Format: Xh Ym Zs (Bambu/OrcaSlicer/PrusaSlicer)
  const hmsMatch = timeStr.match(
    /(?:(\d+)\s*h)?\s*(?:(\d+)\s*m)?\s*(?:(\d+)\s*s)?/
  );
  if (hmsMatch && (hmsMatch[1] || hmsMatch[2] || hmsMatch[3])) {
    const hours = parseInt(hmsMatch[1] || "0", 10);
    const minutes = parseInt(hmsMatch[2] || "0", 10);
    const seconds = parseInt(hmsMatch[3] || "0", 10);
    return Math.round(hours * 60 + minutes + seconds / 60);
  }

  // Format: plain seconds
  const secondsMatch = timeStr.match(/^(\d+)$/);
  if (secondsMatch) {
    return Math.round(parseInt(secondsMatch[1], 10) / 60);
  }

  return null;
}

/**
 * Parse G-code text and extract slicer metadata from comment lines.
 * Only scans comment lines (starting with ;) — typically in the header.
 */
export function parseGcode(text: string, filename: string): GcodeEstimates {
  const result: GcodeEstimates = {
    weightG: null,
    printTimeMinutes: null,
    materialType: null,
    layerHeight: null,
    nozzleTemp: null,
    bedTemp: null,
    filename,
    slicer: null,
  };

  // Split into lines — only process comment lines for efficiency
  const lines = text.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed.startsWith(";")) continue;

    // Remove the leading ; and trim
    const comment = trimmed.slice(1).trim();
    const lower = comment.toLowerCase();

    // --- Slicer detection ---
    if (lower.startsWith("generated by")) {
      result.slicer = comment.replace(/^generated by\s*/i, "").trim();
    } else if (lower.startsWith("bambu studio")) {
      result.slicer = result.slicer || "Bambu Studio";
    }

    // --- Weight (filament used in grams) ---
    // Bambu/OrcaSlicer: "; total filament used [g] = 12.34"
    if (lower.includes("total filament used [g]")) {
      const match = comment.match(/=\s*([\d.]+)/);
      if (match) result.weightG = parseFloat(match[1]);
    }
    // PrusaSlicer: "; filament used [g] = 12.34"
    else if (
      lower.includes("filament used [g]") &&
      !lower.includes("total")
    ) {
      const match = comment.match(/=\s*([\d.]+)/);
      if (match && !result.weightG) result.weightG = parseFloat(match[1]);
    }
    // Cura: ";Filament weight = 12.3"
    else if (lower.startsWith("filament weight")) {
      const match = comment.match(/=\s*([\d.]+)/);
      if (match && !result.weightG) result.weightG = parseFloat(match[1]);
    }

    // --- Print time ---
    // Bambu/OrcaSlicer: "; estimated printing time (normal mode) = 1h 23m 45s"
    if (lower.includes("estimated printing time")) {
      const match = comment.match(/=\s*(.+)$/);
      if (match) {
        const time = parseTimeString(match[1].trim());
        if (time) result.printTimeMinutes = time;
      }
    }
    // Cura: ";TIME:5040" (seconds)
    else if (lower.startsWith("time:")) {
      const match = comment.match(/time:\s*(\d+)/i);
      if (match && !result.printTimeMinutes) {
        result.printTimeMinutes = Math.round(parseInt(match[1], 10) / 60);
      }
    }

    // --- Material type ---
    // "; filament_type = PLA"
    if (lower.startsWith("filament_type")) {
      const match = comment.match(/=\s*(.+)/);
      if (match) result.materialType = match[1].trim();
    }

    // --- Layer height ---
    // "; layer_height = 0.2"
    if (lower.startsWith("layer_height") && !lower.includes("first")) {
      const match = comment.match(/=\s*([\d.]+)/);
      if (match) result.layerHeight = parseFloat(match[1]);
    }

    // --- Nozzle temperature ---
    // "; nozzle_temperature = 220"
    if (lower.startsWith("nozzle_temperature") && !lower.includes("initial")) {
      const match = comment.match(/=\s*([\d.]+)/);
      if (match) result.nozzleTemp = parseFloat(match[1]);
    }

    // --- Bed temperature ---
    // "; bed_temperature = 60"
    if (lower.startsWith("bed_temperature") && !lower.includes("initial")) {
      const match = comment.match(/=\s*([\d.]+)/);
      if (match) result.bedTemp = parseFloat(match[1]);
    }
  }

  // Round weight to 0.1g for clean display
  if (result.weightG !== null) {
    result.weightG = Math.round(result.weightG * 10) / 10;
  }

  return result;
}

/**
 * Check if a file is a G-code file by extension.
 */
export function isGcodeFile(filename: string): boolean {
  const lower = filename.toLowerCase();
  return lower.endsWith(".gcode") || lower.endsWith(".gco") || lower.endsWith(".g");
}
