-- AlterTable
ALTER TABLE "Job" ADD COLUMN "clientId" TEXT;
ALTER TABLE "Job" ADD COLUMN "price" DOUBLE PRECISION;

-- AddForeignKey
ALTER TABLE "Job" ADD CONSTRAINT "Job_clientId_fkey" FOREIGN KEY ("clientId") REFERENCES "Client"("id") ON DELETE SET NULL ON UPDATE CASCADE;
